---
title: "Basic database operations"
output: html_notebook
---

## Load packages

```{r packages, message=FALSE}
library(DBI)
library(dplyr)
```

## Connect

```{r connect}
# Connect with a DSN
con <- dbConnect(odbc::odbc(), "Teradata")
```

## Connection details

```{r}
# Connect with config package
dw <- config::get(file = "teradata/config.yml")
con <- dbConnect(odbc::odbc(),
                 Driver   = dw$driver,
                 DBCName  = dw$DBCName,
                 Username = dw$Username,
                 Password = dw$Password,
                 Database = dw$database,
                 UseXViews = 1
                 )

# Check for a valid connection
dbIsValid(con)

# Disconnect
#dbDisconnect(con)
```

## RStudio connection snippet

```{bash snippet}
cat /etc/rstudio/connections/Teradata
```

## List tables

```{r}
as.data.frame(dbListTables(con))
```

## Create and remove tables

```{r}
mydata <- as.data.frame(CO2)
dbWriteTable(con, "CO2", mydata, overwrite = TRUE)
dbExistsTable(con, "CO2")
dbGetQuery(con, "SELECT * from CO2")
dbRemoveTable(con, "CO2")
dbExistsTable(con, "CO2")
```

## Query Tables

```{r}
dbReadTable(con, "bank")
dbGetQuery(con, "select count(*) from bank")
dbGetQuery(con,'
  select "month_idx", "year", "month",
  sum(case when "term_deposit" = \'yes\' then 1.0 else 0.0 end) as subscribe,
  count(*) as total
  from "bank"
  group by "month_idx", "year", "month"
')
```

## Query tables with dplyr

```{r}
bank_tbl <- tbl(con, "bank")

q1 <- bank_tbl %>%
  group_by(month_idx, year, month) %>%
  summarise(
    subscribe = sum(ifelse(term_deposit == "yes", 1, 0)),
    total = n())

show_query(q1)
```

## Query tables with SQL language engine

```{sql, connection=con, output.var = "mydataframe"}
SELECT "month_idx", "year", "month", SUM(CASE WHEN ("term_deposit" = 'yes') THEN (1.0) ELSE (0.0) END) AS "subscribe",
COUNT(*) AS "total"
FROM ("bank") 
GROUP BY "month_idx", "year", "month"
```

## Reference tables in other databases

```{r}
inventory_tbl <- tbl(con, dbplyr::in_schema("ADW_RSTU", "Inventory"))
inventory_tbl
```

## Volatile tables

```{r}
mtcars_vt <- dbWriteTable(con, "mtcars_vt", mtcars, temporary = TRUE)
dbReadTable(con, "mtcars_vt")
dbGetQuery(con, "HELP VOLATILE TABLE")
dbRemoveTable(con, "mtcars_vt")
```

## Execute SQL statements

```{r}
dbExecute(con, "create table iris2 as iris with data")
dbReadTable(con, "iris2")
dbRemoveTable(con, "iris2")
```

## SQL Specific translations

```{r}
# log --> LN
tbl(con, "cars") %>% mutate(log(wt)) %>% show_query()

# log10 --> LOG
tbl(con, "cars") %>% mutate(log10(wt)) %>% show_query()

# var --> VAR_SAMP
tbl(con, "cars") %>% summarize(var(wt)) %>% show_query()

# sd --> STDDEV_SAMP
tbl(con, "cars") %>% summarize(sd(wt)) %>% show_query()
```
